"""empty message

Revision ID: 2633cf8bf7b6
Revises: 
Create Date: 2023-10-08 22:29:51.130295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2633cf8bf7b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastperioddate', sa.Date(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_periodlength')
        batch_op.drop_column('user_cyclength')
        batch_op.drop_column('user_lastperioddate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_lastperioddate', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('user_cyclength', mysql.INTEGER(display_width=11), server_default=sa.text('28'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_periodlength', mysql.INTEGER(display_width=11), server_default=sa.text('7'), autoincrement=False, nullable=False))

    with op.batch_alter_table('cycle_entry', schema=None) as batch_op:
        batch_op.drop_column('lastperioddate')

    # ### end Alembic commands ###
