"""empty message

Revision ID: 38c8a2f57122
Revises: 99fc435838ef
Create Date: 2023-10-18 19:49:13.877394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38c8a2f57122'
down_revision = '99fc435838ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.alter_column('date_recorded',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('symptoms_tracking', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms_tracking', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.alter_column('date_recorded',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
