"""empty message

Revision ID: 431f88713b11
Revises: c10705674bfe
Create Date: 2023-10-13 01:04:52.518151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '431f88713b11'
down_revision = 'c10705674bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.alter_column('mood_swing',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('1', '0'),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pix', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_pix')

    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.alter_column('mood_swing',
               existing_type=sa.Enum('1', '0'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
