"""empty message

Revision ID: 99fc435838ef
Revises: 431f88713b11
Create Date: 2023-10-18 17:38:50.732902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99fc435838ef'
down_revision = '431f88713b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'symptoms_tracking', ['symptom_id'], ['symptom_id'])
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('symptom_id')

    # ### end Alembic commands ###
