"""empty message

Revision ID: c10705674bfe
Revises: 2633cf8bf7b6
Create Date: 2023-10-10 18:28:54.914662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c10705674bfe'
down_revision = '2633cf8bf7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_entry', schema=None) as batch_op:
        batch_op.drop_constraint('cycle_entry_ibfk_2', type_='foreignkey')
        batch_op.drop_column('cyc_sys_id')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('symptoms_tracking', schema=None) as batch_op:
        batch_op.alter_column('symptom_type',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms_tracking', schema=None) as batch_op:
        batch_op.alter_column('symptom_type',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)

    with op.batch_alter_table('cycle_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('cyc_sys_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cycle_entry_ibfk_2', 'symptoms_tracking', ['cyc_sys_id'], ['symptom_id'])

    # ### end Alembic commands ###
