"""empty message

Revision ID: da19d695f47b
Revises: 38c8a2f57122
Create Date: 2023-10-19 08:39:02.509390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da19d695f47b'
down_revision = '38c8a2f57122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('medication')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
